Resume.Web/Areas/Admin/Components/LeftSideBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Resume.Bussines.Extensions;
using Resume.Bussines.Services.Interface;

namespace Resume.Web.Areas.Admin.Components;

public class LeftSideBarViewComponent : ViewComponent
{
    #region Fields

    private readonly IUserService _userService;

    #endregion

    #region Constructor

    public LeftSideBarViewComponent(IUserService userService)
    {
        _userService = userService;
    }

    #endregion

    #region Methods

    public async Task<IViewComponentResult> InvokeAsync()
    {
        ViewData["User"] = await _userService.GetInformationAsync(User.GetUserId());
        return View("LeftSideBar");
    }

    #endregion
}

Resume.Web/Areas/Admin/Controllers/ActivityController.cs
using Microsoft.AspNetCore.Mvc;
using Resume.Bussines.Services.Interface;
using Resume.DAL.ViewModels.Activity;
using Resume.DAL.ViewModels.ContactUs;

namespace Resume.Web.Areas.Admin.Controllers
{
    public class ActivityController : AdminBaseController
    {
        #region Fields

        private readonly IActivityService _activityService;

        #endregion

        #region Constructor

        public ActivityController(IActivityService activityService)
        {
            _activityService = activityService;
        }

        #endregion

        #region Actions

        #region List

        public async Task<IActionResult> List(FilterActivityViewModel filter)
        {
            var model = await _activityService.FilterAsync(filter);

            return View(model);
        }

        #endregion

        #region Create

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateActivityViewModel model)
        {
            #region Validations

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            #endregion

            var result = await _activityService.CreateAsync(model);
            switch (result)
            {
                case CreateActivityResult.Success:
                    TempData[SuccessMessage] = "فعالیت جدید با موفقیت اضافه شد.";
                    return RedirectToAction("List");

                case CreateActivityResult.Error:
                    TempData[ErrorMessage] = "خطایی رخ داده است.";
                    break;

            }

            return View(model);
        }

        #endregion

        #region Edit

        public async Task<IActionResult> Update(int id)
        {
            var model = await _activityService.GetInfoByIdAsync(id);

            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Update(EditActivityViewModel model)
        {
            #region Validations

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            #endregion

            var result = await _activityService.UpdateAsync(model);
            switch (result)
            {
                case EditActivityResult.Success:
                    TempData[SuccessMessage] = "فعالیت با موفقیت ویرایش شد.";
                    return RedirectToAction("List");

                case EditActivityResult.Error:
                    TempData[ErrorMessage] = "خطایی رخ داده است.";
                    break;

                case EditActivityResult.ActivityNotFound:
                    TempData[ErrorMessage] = "فعالیتی برای ویرایش پیدا نشد.";
                    break;

            }

            return View(model);
        }


        #endregion

        #endregion

    }
}

Resume.Web/Areas/Admin/Controllers/ContactUsController.cs
using Microsoft.AspNetCore.Mvc;
using Resume.Bussines.Services.Interface;
using Resume.DAL.ViewModels.ContactUs;
using Resume.DAL.ViewModels.User;

namespace Resume.Web.Areas.Admin.Controllers
{
    public class ContactUsController : AdminBaseController
    {
        #region Fields

        private readonly IContactUsService _contactUsService;

        #endregion

        #region Constructor

        public ContactUsController(IContactUsService contactUsService)
        {
            _contactUsService = contactUsService;
        }

        #endregion


        #region Actions

        #region List

        public async Task<IActionResult> List(FilterContactUsViewModel filter)
        {
            var model = await _contactUsService.FilterAsync(filter);
            return View(model);
        }

        #endregion

        #region Details

        public async Task<IActionResult> Details(int id)
        {
            var contactUs = await _contactUsService.GetByIdAsync(id);

            if (contactUs == null)
            {
                return NotFound();
            }

            return View(contactUs);
        }

        [HttpPost]
        public async Task<IActionResult> Details(ContactUsDetailsViewModel model)
        {
            #region Validations

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            #endregion

            var result = await _contactUsService.AnswerAsync(model);
            switch (result)
            {
                case AnswerResult.Success:
                    TempData[SuccessMessage] = "پاسخ برای این تماس با ما ارسال شد.";
                    return RedirectToAction("List");

                case AnswerResult.ContactUsNotFound:
                    TempData[ErrorMessage] = "تماس با ما پیدا نشد.";
                    break;

                case AnswerResult.AnswerIsNull:
                    TempData[ErrorMessage] = "متن پاسخ خالی است.";
                    break;

            }

            return View(model);
        }

        #endregion

        #endregion

    }
}

Resume.Web/Areas/Admin/Controllers/EducationController.cs
using Microsoft.AspNetCore.Mvc;
using Resume.Bussines.Services.Interface;
using Resume.DAL.ViewModels.Education;

namespace Resume.Web.Areas.Admin.Controllers;

public class EducationController : AdminBaseController
{
    #region Fields

    private readonly IEducationService _educationService;

    #endregion

    #region Constructor

    public EducationController(IEducationService educationService)
    {
        _educationService = educationService;
    }

    #endregion

    #region Actions

    #region List

    public async Task<IActionResult> List(FilterEducationViewModel filter)
    {
        var model = await _educationService.FilterAsync(filter);
        return View(model);
    }

    #endregion

    #region Create

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(CreateEducationViewModel model)
    {
        #region Validations

        if (!ModelState.IsValid)
        {
            return View(model);
        }

        #endregion

        var result = await _educationService.CreateAsync(model);
        switch (result)
        {
            case CreateEducationResult.Success:
                TempData[SuccessMessage] = "عملیات با موفقیت انجام شد.";
                return RedirectToAction("List");

            case CreateEducationResult.Error:
                TempData[ErrorMessage] = "عملیات با شکست مواجه شد.";
                break;
        }

        return View(model);
    }

    #endregion

    #region Edit

    public async Task<IActionResult> Edit(int id)
    {
        var model = await _educationService.GetForEditByIdAsync(id);

        if (model == null)
            return NotFound();

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(EditEducationViewModel model)
    {
        #region Validations

        if (!ModelState.IsValid)
        {
            return View(model);
        }

        #endregion

        var result = await _educationService.EditAsync(model);
        switch (result)
        {
            case EditEducationResult.Success:
                TempData[SuccessMessage] = "عملیات با موفقیت انجام شد.";
                return RedirectToAction("List");

            case EditEducationResult.Error:
                TempData[ErrorMessage] = "عملیات با شکست مواجه شد.";
                break;

            case EditEducationResult.EducationNotFound:
                TempData[ErrorMessage] = "تحصیلات پیدا نشد.";
                break;
        }

        return View(model);
    }

    #endregion

    #endregion
}

Resume.Web/Components/EducationViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Resume.Bussines.Services.Interface;
using Resume.DAL.ViewModels.Education;

namespace Resume.Web.Components;

public class EducationViewComponent : ViewComponent
{
    #region Fields

    private readonly IEducationService _educationService;

    #endregion

    #region Constructor

    public EducationViewComponent(IEducationService educationService)
    {
        _educationService = educationService;
    }

    #endregion

    #region Methods

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var model = await _educationService.FilterAsync(new FilterEducationViewModel()
        {
        });

        return View("Education", model);
    }

    #endregion
}

Resume.Web/Components/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Resume.Bussines.Services.Interface;

namespace Resume.Web.Components;

public class HeaderViewComponent:ViewComponent
{
    #region Fields

    private readonly IAboutMeService _aboutMeService;

    #endregion

    #region Constructor

    public HeaderViewComponent(IAboutMeService aboutMeService)
    {
        _aboutMeService = aboutMeService;
    }

    #endregion

    #region Method

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var model = await _aboutMeService.GetClientSideInfoAsync();
        return View("Header", model);
    }

    #endregion
}

Resume.Web/Components/MyActivityViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Resume.Bussines.Services.Interface;

namespace Resume.Web.Components
{
	public class MyActivityViewComponent : ViewComponent
	{

		#region Fields

		private readonly IActivityService _activityService;

		#endregion

		#region Constructor

		public MyActivityViewComponent(IActivityService activityService)
		{
			_activityService = activityService;
		}

		#endregion

		#region Method

		public async Task<IViewComponentResult> InvokeAsync()
		{
			var model = await _activityService.GetAllInfo();
			return View("MyActivity", model);
		}

		#endregion
	}
}

Resume.Web/Controllers/AboutMeController.cs
using Microsoft.AspNetCore.Mvc;
using Resume.Bussines.Services.Interface;

namespace Resume.Web.Controllers
{
    public class AboutMeController : SiteBaseController
    {
        #region Fields

        private readonly IAboutMeService _aboutMeService;

        #endregion

        #region Constructor

        public AboutMeController(IAboutMeService aboutMeService)
        {
            _aboutMeService = aboutMeService;
        }

        #endregion

        #region Actions

        #region Index

        [HttpGet("/")]
        public async Task<IActionResult> Index()
        {
            var model = await _aboutMeService.GetClientSideInfoAsync();
            return View(model);
        }

        #endregion

        #endregion
    }
}

Resume.Web/Areas/Admin/Views/Shared/Components/LeftSideBar/LeftSideBar.cshtml
@using Resume.DAL.ViewModels.User
@{
    UserDetailsViewModel user = ViewData["User"] as UserDetailsViewModel ?? new UserDetailsViewModel();
}
<div>
    <aside id="leftsidebar" class="sidebar">
        <div class="menu">
            <ul class="list">
                <li>
                    <div class="sidebar-profile clearfix">
                        <div class="profile-img">
                            <img src="/Admin/assets/images/usrbig.jpg" alt="profile">
                        </div>
                        <div class="profile-info">
                            <h3>@user.FirstName @user.LastName</h3>
                            <p>خوش آمدید !</p>
                        </div>
                    </div>
                </li>
                <li>
                    <a href="#" onClick="return false;" class="menu-toggle">
                        <i class="menu-icon ti-user"></i>
                        <span>مدیریت کاربران</span>
                    </a>
                    <ul class="ml-menu">
                        <li class="active">
                            <a asp-area="Admin" asp-controller="User" asp-action="List">لیست کاربران</a>
                        </li>
                        <li class="active">
                            <a asp-area="Admin" asp-controller="User" asp-action="Create">افزودن کاربر</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#" onClick="return false;" class="menu-toggle">
                        <i class="menu-icon ti-user"></i>
                        <span>مدیریت تماس با ما</span>
                    </a>
                    <ul class="ml-menu">
                        <li class="active">
                            <a asp-area="Admin" asp-controller="ContactUs" asp-action="List">لیست تماس با ما</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#" onClick="return false;" class="menu-toggle">
                        <i class="menu-icon ti-user"></i>
                        <span>مدیریت درباره ی من</span>
                    </a>
                    <ul class="ml-menu">
                        <li class="active">
                            <a asp-area="Admin" asp-controller="AboutMe" asp-action="Edit">درباره ی من</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#" onClick="return false;" class="menu-toggle">
                        <i class="menu-icon ti-user"></i>
                        <span>مدیریت فعالیت های من</span>
                    </a>
                    <ul class="ml-menu">
                        <li class="active">
                            <a asp-area="Admin" asp-controller="Activity" asp-action="List">لیست فعالیت های من</a>
                        </li>
                        <li class="active">
                            <a asp-area="Admin" asp-controller="Activity" asp-action="Create">افزودن فعالیت</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#" onClick="return false;" class="menu-toggle">
                        <i class="menu-icon ti-user"></i>
                        <span>مدیریت تحصیلات من</span>
                    </a>
                    <ul class="ml-menu">
                        <li class="active">
                            <a asp-area="Admin" asp-controller="Education" asp-action="List">لیست تحصیلات من</a>
                        </li>
                        <li class="active">
                            <a asp-area="Admin" asp-controller="Education" asp-action="Create">افزودن تحصیلات</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </aside>
</div>