Resume.Web/Components/EducationViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Resume.Bussines.Services.Interface;
using Resume.DAL.ViewModels.Education;

namespace Resume.Web.Components;

public class EducationViewComponent : ViewComponent
{
    #region Fields

    private readonly IEducationService _educationService;

    #endregion

    #region Constructor

    public EducationViewComponent(IEducationService educationService)
    {
        _educationService = educationService;
    }

    #endregion

    #region Methods

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var model = await _educationService.FilterAsync(new FilterEducationViewModel()
        {
        });

        return View("Education", model);
    }

    #endregion
}

Resume.Web/Controllers/ResumeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Resume.Web.Controllers;

public class ResumeController:SiteBaseController
{
    #region Actions

    #region Index

    [HttpGet("/resume")]
    public IActionResult Index()
    {
        return View();
    }

    #endregion

    #endregion
}

Resume.Web/Views/Resume/Index.cshtml
@{
    ViewData["Title"] = "رزومه";
}

<div class="box box-content">
    <div class="pb-2">
        <h1 class="title title--h1 first-title title__separate">رزومه</h1>
    </div>

    <!-- Experience -->
    <div class="row">
        @await Component.InvokeAsync("Education")
        
        <div class="col-12">
            <h2 class="title title--h3"><img class="title-icon" src="/Site/assets/icons/icon-experience.svg" alt=""/> تجربه</h2>
            <div class="timeline">
                <!-- Item -->
                <article class="timeline__item">
                    <h5 class="title title--h5 timeline__title">کارگردان خلاق</h5>
                    <span class="timeline__period">1395-حاضر</span>
                    <p class="timeline__description">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است</p>
                </article>

                <!-- Item -->
                <article class="timeline__item">
                    <h5 class="title title--h5 timeline__title">کارگردان هنری</h5>
                    <span class="timeline__period">1393 - 1395</span>
                    <p class="timeline__description">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است</p>
                </article>

                <!-- Item -->
                <article class="timeline__item">
                    <h5 class="title title--h5 timeline__title">طراح وب</h5>
                    <span class="timeline__period">1390 - 1393</span>
                    <p class="timeline__description">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است</p>
                </article>
            </div>
        </div>
    </div>
    

    <!-- Skills -->
    <div class="row">
        <div class="col-12">
            <h2 class="title title--h3">مهارت های من</h2>
            <div class="box box__border">
                <!-- Progress -->
                <div class="progress">
                    <div class="progress-bar" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100">
                        <div class="progress-text">
                            <span>طراحی وب</span><span>80%</span>
                        </div>
                    </div>
                    <div class="progress-text">
                        <span>طراحی وب</span>
                    </div>
                </div>

                <!-- Progress -->
                <div class="progress">
                    <div class="progress-bar" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">
                        <div class="progress-text">
                            <span>طراحی گرافیک</span><span>75%</span>
                        </div>
                    </div>
                    <div class="progress-text">
                        <span>طراحی گرافیک</span>
                    </div>
                </div>

                <!-- Progress -->
                <div class="progress">
                    <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100">
                        <div class="progress-text">
                            <span>فتوشاپ</span><span>90%</span>
                        </div>
                    </div>
                    <div class="progress-text">
                        <span>فتوشاپ</span>
                    </div>
                </div>

                <!-- Progress -->
                <div class="progress">
                    <div class="progress-bar" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">
                        <div class="progress-text">
                            <span>الستریتور</span><span>50%</span>
                        </div>
                    </div>
                    <div class="progress-text">
                        <span>الستریتور</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>